### ISSUE TITLE
Tester feedback: language

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-MotionToStayGeneral#14]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `legal issues raised`
language | In the list of issues, there remains summary process specific language.  That should be removed, i.e., references to the summary process statute (G.L. c. 239, s. 5) and the Uniform Summary Process Rules.
Other information | 
Variable being sought | `legal_issues`
Package version | `0.0.1`
Maturity target | Level 1 - this needs to be fixed to be equivalent to the blank form
Tester contact info | Paul Tuttle

**Comment by miabonardi** [comment]
Done.
